title: Rodrigo Eiras
description: "#datascience #cloudcomputing #artificialintelligence #spotfire #osdu #azure #aws"
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

header_pages:
  - about.md
  - projects.md
  - contact.md
